global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'laravel'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:9000']
    scrape_interval: 30s

  - job_name: 'nginx'
    metrics_path: '/nginx_status'
    static_configs:
      - targets: ['webserver:80']
    scrape_interval: 60s

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']
    scrape_interval: 60s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s
